### ISSUE TITLE
After restart - playlist lost

### ISSUE THREAD

**Issue by michalterbert** [hassio-addons/addon-mopidy#99]
# Problem/Motivation
After restart mopidy addon, mopidy lost all playlists

## Expected behavior

Persistence volume for playlists?
## Actual behavior

No more playlists
## Steps to reproduce

Install, start, add some URL to playlist and restart :)
## Proposed changes

More details:
Mopidy Current version: 3c1b37e 
core-2021.2.3
supervisor-2021.02.9
Home Assistant OS 5.11

**Comment by michalterbert** [comment]
One more screen from docker container:
![image](https://user-images.githubusercontent.com/15417117/108173130-0acad080-70fe-11eb-9139-e7f0b77dcce7.png)

**Comment by pescheck-bram** [comment]
Yes, this is because it will destroy the image and up it... If you create a share with https://github.com/home-assistant/addons/tree/master/samba for example you could make sure the m3u is persistent even after a restart. You could set the path with this plugin:
https://docs.mopidy.com/en/latest/ext/m3u/

So steps to do this:
- Use SMB or a samba addon
- Create share
- Make sure the m3u is located to the share

And this will be persistent and you won't have this problem anymore.

**Comment by michalterbert** [comment]
@pescheck-bram thanks for solution 👍

**Comment by brammittendorff** [comment]
No problem, good luck!
